### ISSUE TITLE
Link delay is actually round-trip time

### ISSUE THREAD

**Issue by soutzis** [coreemu/core#145] opened 2018-03-09 12:47 UTC
When a symmetric link effects "delay" is configured by the user, it is set as the round-trip time instead. For example, if you set the delay of a symmetric link to 50000us, in reality the delay will be set to 25ms and the rtt to 50ms.

-Soutzis

**Comment by Kevlar** [comment] 2019-06-06 16:21
We confirmed this in cases where switches are used (delay works in router-only networks).  We'll look into fixing it.  Thanks!

**Comment by bharnden** [comment] 2020-05-09 17:54
After talking things over, the current behavior is the desired behavior and expected. We can work to update documentation in relation to using this since it will provide better context.

In peer to peer nodes TC is applied to each interface. So the effect is both ways by default. The GUI does provide a way to manipulate it for each direction though, likely to help achieve what you desire. With the right settings.

Also to note, since CORE is applying the TC configuration to the veth sibling of a nodes interface the actual impact is on a nodes incoming traffic and not outgoing as TC itself notes in its documentation.

Closing for now and will look to improve documentation related to this.

**Closed by bharnden** 2020-05-09 17:54 UTC
Labels: bug
